//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetTypeTable
    {
        public decimal BetTypeID { get; set; }
        public string BetDescription { get; set; }
        public Nullable<int> BetCategory { get; set; }
        public Nullable<int> BetValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
