//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetPlacedTable
    {
        public decimal BetPlacedID { get; set; }
        public decimal UserID { get; set; }
        public decimal GameID { get; set; }
        public decimal BetTypeID { get; set; }
        public Nullable<int> BetCategory { get; set; }
        public Nullable<decimal> TeamID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
