//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetResultsTable
    {
        public decimal BetResultsID { get; set; }
        public Nullable<decimal> BetPlacedID { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
