//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public decimal UserID { get; set; }
        public string MastekID { get; set; }
        public Nullable<decimal> Employee_ID { get; set; }
        public string User_Name { get; set; }
        public string Project { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
